# Generated by Django 2.2.5 on 2020-01-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='status',
            field=models.CharField(max_length=264),
        ),
    ]
